## Pengenalan Dasar-Dasar Pemrograman Dengan Bahasa Python
1. Menampilkan hello world
2. Input dan Output
3. Runtunan, Percabangan, Perulangan
4. Array
5. Membuat Fungsi 
6. Menggunakan Fungsi Build-in

In [1]:
# Menampilkan hello world
print("Hello World") # menggunakan tanda ("") karena bertipe strin

Hello World


In [2]:
print(100) # tanpa tanda ("") karena bertipe numerikik

100


In [3]:
# Input dan output secara default
nama = "Aryajaya Alamsyah, S.Kom"

In [4]:
print(nama)

Aryajaya Alamsyah, S.Kom


In [5]:
# input dari keyboard
nama = input("Masukan Nama : ")
print("Selamat Pagi, "+nama)

Selamat Pagi, Aryajaya Alamsyah


In [6]:
# Runtunan 1. secara default

# input
panjang = 5
lebar = 5
tinggi = 10

# proses
volume = panjang * lebar * tinggi

# output
print("Volume balok : "+str(volume))

Volume balok : 250


In [7]:
# Runtunan 1. input dari keyboard

# input
panjang = input("Masukan panjang : ")
lebar = input("Masukan lebar : ")
tinggi = input("Masukan tinggi : ")

# proses. (input diconvert menjadi float)
volume = float(panjang) * float(lebar) * float(tinggi)

# output
print(volume)

500.0


In [8]:
# percabangan. menentukan bilangan ganjil atau genap
# if di python-3.6x tidak menggunakan tanda kurung "()" dan kurawal "{}"
# Bahasa pemrograman lain
# if(kondisi){
#   // statment
# } 

# input
bilangan = 11

# proses
if bilangan % 2 == 0:
    print("Bilangan Genap") # output
else:
    print("Bilangan Ganjil") # output

Bilangan Ganjil


In [9]:
# percabangan. menentukan huruf mutu

# input
nilai = 70

# proses 
if nilai >= 80:
    print("A") # input
elif nilai >= 70:
    print("B")
elif nilai >= 60:
    print("C")
elif nilai >= 70:
    print("D")
else:
    print("E")

B


In [10]:
# perulangan. Menghitung faktorial

# input
bilangan = 5
faktorial = 1

# proses
for i in range(1, bilangan + 1):
    faktorial = faktorial * i
    
# output
print("Faktorial dari", bilangan, "adalah", faktorial)

Faktorial dari 5 adalah 120


In [11]:
# Array. Menampilkan element yang ada didalam list

# input array
mk = ["Data Mining", "Data Spatial", "Machine Learning", "Deep Learning", "Statistik Komputasi"]

# proses
print("Mata kuliah sebanyak",format(len(mk)),"\n")
for i in mk:
    print(i)

Mata kuliah sebanyak 5 

Data Mining
Data Spatial
Machine Learning
Deep Learning
Statistik Komputasi


In [12]:
# Array. Menjumlahkan 2 buah matrik

# input
mat1 = [
    [5, 0],
    [2, 6],
]

mat2 = [
    [1, 0],
    [4, 2],
]

# proses kaidah ddp
# menggunakan nested loop
for x in range(0, len(mat1)):
    for y in range(0, len(mat1[0])):
        print (mat1[x][y] + mat2[x][y], end=" ") # output
    print(" ")

6 0  
6 8  


In [13]:
# Array. Menjumlahkan 2 buah matrik
# Deklarasi pustaka numpy
import numpy as np;

# input
mat1 = [
    [5, 0],
    [2, 6],
]
mat1 = np.array(mat1)

mat2 = [
    [1, 0],
    [4, 2],
]
mat2 = np.array(mat2)

# proses kaidah python
# menggunakan runtunan
mat3 = mat1 + mat2 # proses

print(mat3) # output

[[6 0]
 [6 8]]


In [14]:
# Membuat Fungsi. menjumlahkan array dengan fungsi (def)

# fungsi lbr_matriks dan pjg_matriks untuk menentukan ukuran dimensi array
def lbr_matriks(matriks):
    return len(matriks)

def pjg_matriks(matriks):
    return len(matriks[0])

# fungsi untuk menjumlahkan arrray
def jumlahkan_matriks(mat_a, mat_b):
    temp_row = []
    temp_mat = [] 
    for i in range(0, lbr_matriks(mat_a)):
        for j in range(0, pjg_matriks(mat_a)):
            temp_row.append(mat_a[i][j] + mat_b[i][j])
        temp_mat.append(temp_row)
        temp_row = []
    return temp_mat

# fungsi untuk menampilkan isi array
def cetak_matriks(matriks):
    for row in matriks:
        print (row)

In [15]:
# input array
matriks_a = [[1, 2, 3, 4], [5, 6, 7, 8]]
matriks_b = [[1, 1, 1, 1], [1, 1, 1, 1]]

# proses
hasil = jumlahkan_matriks(matriks_a, matriks_b)

# output
print ("matriks_a : ")
cetak_matriks(matriks_a)

print ("\nmatriks_b : ")
cetak_matriks(matriks_b)

print ("\nhasil penjumlahan :")
cetak_matriks(hasil)

matriks_a : 
[1, 2, 3, 4]
[5, 6, 7, 8]

matriks_b : 
[1, 1, 1, 1]
[1, 1, 1, 1]

hasil penjumlahan :
[2, 3, 4, 5]
[6, 7, 8, 9]


In [16]:
# load lib numpy
import numpy as np

# input menggunakan numpy
# np.array()
matriks_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matriks_b = np.array([[1, 1, 1, 1], [1, 1, 1, 1]])

# proses
matriks_c = matriks_a + matriks_b

#output
print(matriks_c)

[[2 3 4 5]
 [6 7 8 9]]


In [17]:
# load lib numpy
import numpy as np

# definisi nilai array dengan numpy
array = np.array([ [1, 2], [3, 4], [5, 6] ])

# menjumlahkan element array
total = np.sum(array)

# menampilkan hasil
print("Hasil jumlah semua elemen array adalah",total)

Hasil jumlah semua elemen array adalah 21
